"""Mark responses as resolved

Revision ID: 0210dc9b2f44
Revises: c98febd779c6
Create Date: 2019-03-26 20:04:43.331293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0210dc9b2f44'
down_revision = 'c98febd779c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('resolved', sa. Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'resolved')
    # ### end Alembic commands ###
