"""rename block model to office

Revision ID: 027c4eccfc78
Revises: 26c14e799a0f
Create Date: 2018-07-02 18:05:33.358784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027c4eccfc78'
down_revision = '26c14e799a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('floors_block_id_fkey', 'floors', type_='foreignkey')
    op.drop_table('blocks')
    op.add_column('floors', sa.Column('office_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'floors', 'offices', ['office_id'], ['id'])
    op.drop_column('floors', 'block_id')
    op.add_column('resources', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'quantity')
    op.add_column('floors', sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'floors', type_='foreignkey')
    op.create_foreign_key('floors_block_id_fkey', 'floors', 'blocks', ['block_id'], ['id'])
    op.drop_column('floors', 'office_id')
    op.create_table('blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='blocks_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blocks_pkey')
    )
    op.drop_table('offices')
    # ### end Alembic commands ###
