"""Add field for activating and deactivating a question

Revision ID: 0a95059767eb
Revises: 5f9ad1c6faa2
Create Date: 2018-12-20 09:15:58.712162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a95059767eb'
down_revision = '5f9ad1c6faa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_active')
    # ### end Alembic commands ###
