"""Remove room_id column from Resource model

Revision ID: 0ecc55aca3e7
Revises: 903c8f91f030
Create Date: 2019-04-03 17:17:32.773424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecc55aca3e7'
down_revision = '903c8f91f030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resources_room_id_fkey', 'resources', type_='foreignkey')
    op.drop_column('resources', 'room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resources_room_id_fkey', 'resources', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
