"""Remove old structure code

Revision ID: 0f7bdb8ab991
Revises: 84a1aa841faa
Create Date: 2019-05-27 16:32:15.924951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7bdb8ab991'
down_revision = '84a1aa841faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_structure_id_fkey', 'locations', type_='foreignkey')
    op.drop_column('locations', 'structure_id')
    op.drop_index('ix_structure_name', table_name='structure')
    op.drop_index('structure_level_idx', table_name='structure')
    op.drop_index('structure_lft_idx', table_name='structure')
    op.drop_index('structure_rgt_idx', table_name='structure')
    op.drop_table('structure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lft', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rgt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tree_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['structure.id'], name='structure_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='structure_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='structure_pkey')
    )
    op.create_index('structure_rgt_idx', 'structure', ['rgt'], unique=False)
    op.create_index('structure_lft_idx', 'structure', ['lft'], unique=False)
    op.create_index('structure_level_idx', 'structure', ['level'], unique=False)
    op.create_index('ix_structure_name', 'structure', ['name'], unique=True)
    op.add_column('locations', sa.Column('structure_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('locations_structure_id_fkey', 'locations', 'structure', ['structure_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
