"""add the office and wing model

Revision ID: 127ff4285598
Revises: 5a0fcbced74d
Create Date: 2018-07-22 12:38:31.463700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127ff4285598'
down_revision = '5a0fcbced74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blocks', sa.Column('office_id', sa.Integer(), nullable=True))
    op.drop_constraint('blocks_location_id_fkey', 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'offices', ['office_id'], ['id'])
    op.drop_column('blocks', 'location_id')
    op.add_column('rooms', sa.Column('wing_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['name'])
    op.create_foreign_key(None, 'rooms', 'wings', ['wing_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'wing_id')
    op.add_column('blocks', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key('blocks_location_id_fkey', 'blocks', 'locations', ['location_id'], ['id'])
    op.drop_column('blocks', 'office_id')
    op.drop_table('wings')
    op.drop_table('offices')
    # ### end Alembic commands ###
