"""add meeting update notification

Revision ID: 130957ec37be
Revises: ddd2257638a3
Create Date: 2018-10-25 12:42:54.449097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130957ec37be'
down_revision = 'ddd2257638a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('meeting_update_notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'meeting_update_notification')
    # ### end Alembic commands ###
