"""Add calndarId field to room table

Revision ID: 16706f39418e
Revises: c231314bba8d
Create Date: 2018-06-07 15:51:04.456452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16706f39418e'
down_revision = 'c231314bba8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.add_column('rooms', sa.Column('calendar_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'calendar_id')
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_added', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_seen', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='devices_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    # ### end Alembic commands ###
