"""add activity column to devices table

Revision ID: 1b53553ddacf
Revises: c65718cd4ed8
Create Date: 2019-06-22 12:59:24.591339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1b53553ddacf'
down_revision = 'c65718cd4ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    activitytype = postgresql.ENUM('online', 'offline', name='activitytype')
    activitytype.create(op.get_bind())
    op.add_column('devices', sa.Column('activity', sa.Enum(
        'online', 'offline', name='activitytype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'activity')
    op.execute("DROP TYPE activitytype;")
    # ### end Alembic commands ###
