"""add missing_items option to responses questiontype

Revision ID: 1f5e47273894
Revises: 50173cb0491f
Create Date: 2019-07-12 07:46:19.840784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f5e47273894'
down_revision = '50173cb0491f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'question_type')
    questiontype = postgresql.ENUM(
        'check', 'text_area', 'rate', 'missing_items', name='questiontype')
    questiontype.drop(op.get_bind(), checkfirst=False)
    questiontype.create(op.get_bind(), checkfirst=False)
    op.add_column('responses', sa.Column('question_type', sa.Enum('rate', 'check', 'text_area', 'missing_items', name='questiontype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'question_type')
    questiontype = postgresql.ENUM(
        'check', 'text_area', 'rate', name='questiontype')
    questiontype.drop(op.get_bind(), checkfirst=False)
    questiontype.create(op.get_bind(), checkfirst=False)
    op.add_column('responses', sa.Column('question_type', postgresql.ENUM('check', 'text_area', 'rate', name='questiontype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
