"""empty message

Revision ID: 217762976d14
Revises: c231314bba8d
Create Date: 2018-06-09 15:31:36.108837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217762976d14'
down_revision = 'c231314bba8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
