"""Add feedback table

Revision ID: 227a359b6b59
Revises: c3f8cfd2b1c4
Create Date: 2018-11-15 17:59:30.616909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227a359b6b59'
down_revision = 'c3f8cfd2b1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('creation_time', sa.String(), nullable=False),
    sa.Column('overall_rating', sa.String(), nullable=True),
    sa.Column('cleanliness_rating', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
