"""add calendar_id field to room table

Revision ID: 2711dcb76cd4
Revises: 631fe5fea815
Create Date: 2018-06-07 14:11:32.535599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2711dcb76cd4'
down_revision = '631fe5fea815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
