"""Add check_in_time and meeting_end_time to Events model

Revision ID: 395aa731622a
Revises: 67e294b4271c
Create Date: 2019-04-02 09:40:56.591603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395aa731622a'
down_revision = '67e294b4271c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('check_in_time', sa.String(), nullable=True))
    op.add_column('events', sa.Column('meeting_end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'meeting_end_time')
    op.drop_column('events', 'check_in_time')
    # ### end Alembic commands ###
