"""empty message

Revision ID: 3b65ab682a90
Revises: 21f5e1dc628c
Create Date: 2018-06-14 08:37:38.534843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b65ab682a90'
down_revision = '21f5e1dc628c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
