"""add office structure model for hierarchical structure

Revision ID: 3c8552b8520e
Revises: 20dd40a4c970
Create Date: 2019-08-11 14:31:00.684828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c8552b8520e'
down_revision = '20dd40a4c970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structures',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('structures', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.create_index('structures_level_idx', 'structures', ['level'], unique=False)
    op.create_index('structures_lft_idx', 'structures', ['lft'], unique=False)
    op.create_index('structures_rgt_idx', 'structures', ['rgt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('structures_rgt_idx', table_name='structures')
    op.drop_index('structures_lft_idx', table_name='structures')
    op.drop_index('structures_level_idx', table_name='structures')
    op.drop_table('structures')
    # ### end Alembic commands ###
