"""empty message

Revision ID: 3f7330cf19b8
Revises: c231314bba8d
Create Date: 2018-06-12 00:19:17.077540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7330cf19b8'
down_revision = 'c231314bba8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('locations', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('calendar_id', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image_url')
    op.drop_column('rooms', 'calendar_id')
    op.drop_column('locations', 'image_url')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
