"""add statetype to tags

Revision ID: 404358628973
Revises: 8647af58767d
Create Date: 2019-02-04 13:54:58.440677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404358628973'
down_revision = '8647af58767d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'state')
    # ### end Alembic commands ###
