"""Remove room_id from Resource table

Revision ID: 40f600ba71c3
Revises: 63716b3fc0bb
Create Date: 2019-04-09 17:16:44.675927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f600ba71c3'
down_revision = '63716b3fc0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resources_room_id_fkey', 'resources', type_='foreignkey')
    op.drop_column('resources', 'room_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('resources_room_id_fkey', 'resources', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
