"""fix response table

Revision ID: 420bfd812496
Revises: 39e1d16dc864
Create Date: 2018-12-17 12:25:27.299317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420bfd812496'
down_revision = '39e1d16dc864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
