"""set nullable false on state device

Revision ID: 472c199d7d44
Revises: af8e4f84b552
Create Date: 2019-07-22 12:39:21.595504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '472c199d7d44'
down_revision = 'af8e4f84b552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'state')
    op.add_column('devices', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
