"""Relationship between officestructure and location

Revision ID: 4a67981deb58
Revises: 4b0dfa7815d5
Create Date: 2019-03-28 17:45:14.515140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a67981deb58'
down_revision = '4b0dfa7815d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column(
        'office_structures_id', sa.Integer(), nullable=False))
    op.create_foreign_key('locations_office_structures_id_fkey', 'locations', 'office_structures', [
                          'office_structures_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_office_structures_id_fkey',
                       'locations', type_='foreignkey')
    op.drop_column('locations', 'office_structures_id')
    # ### end Alembic commands ###
