"""make roomtype and calendarid optional

Revision ID: 4dc677f14096
Revises: c82fd3524636
Create Date: 2018-08-30 10:51:28.801500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc677f14096'
down_revision = 'c82fd3524636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'calendar_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
