"""Add CheckOptions column to Questions table

Revision ID: 50173cb0491f
Revises: ac2686b45596
Create Date: 2019-05-07 14:47:01.869751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50173cb0491f'
down_revision = 'a5a4841351d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('check_options', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'check_options')
    # ### end Alembic commands ###
