"""empty message

Revision ID: 5355315aa157
Revises: 217762976d14
Create Date: 2018-06-09 15:35:17.204328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5355315aa157'
down_revision = '217762976d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
