"""made wing name unique

Revision ID: 6046c7c7c022
Revises: 227a359b6b59
Create Date: 2018-11-29 11:40:44.274965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6046c7c7c022'
down_revision = '227a359b6b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'wings', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wings', type_='unique')
    # ### end Alembic commands ###
