"""allow NULL values on columns abbreviation in location table

Revision ID: 63716b3fc0bb
Revises: fc9664b94e6b
Create Date: 2019-04-16 11:29:31.831229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63716b3fc0bb'
down_revision = 'fc9664b94e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
