"""Migration message

Revision ID: 661c057a2177
Revises: 3942aff720bb
Create Date: 2019-04-23 13:49:29.029847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661c057a2177'
down_revision = '3942aff720bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
