"""empty message

Revision ID: 6723b223dc1e
Revises: 5189113ab5b6
Create Date: 2018-07-03 13:42:25.214320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6723b223dc1e'
down_revision = '5189113ab5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'country',
               existing_type=postgresql.ENUM('Uganda', 'Kenya', 'Nigeria', name='all_countries'),
               nullable=True)
    op.alter_column('locations', 'time_zone',
               existing_type=postgresql.ENUM('GTM+3', 'GMT+3', 'GMT+1', name='all_timezone'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'time_zone',
               existing_type=postgresql.ENUM('GTM+3', 'GMT+3', 'GMT+1', name='all_timezone'),
               nullable=False)
    op.alter_column('locations', 'country',
               existing_type=postgresql.ENUM('Uganda', 'Kenya', 'Nigeria', name='all_countries'),
               nullable=False)
    # ### end Alembic commands ###
