"""add partial index for seft delete

Revision ID: 67e294b4271c
Revises: ab83c84a325b
Create Date: 2019-02-15 06:54:43.544856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e294b4271c'
down_revision = 'ab83c84a325b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_block_content', 'blocks', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_floor_content', 'floors', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_location_content', 'locations', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_office_content', 'offices', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.drop_constraint('offices_name_key', 'offices', type_='unique')
    op.create_index('ix_unique_question_content', 'questions', ['question'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_resource_content', 'resources', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))    
    op.create_index('ix_unique_room_content', 'rooms', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_tag_content', 'tags', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_index('ix_unique_wing_content', 'wings', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.drop_constraint('wings_name_key', 'wings', type_='unique')
    op.create_index('ix_unique_user_content', 'users', ['name'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wings_name_key', 'wings', ['name'])
    op.drop_index('ix_unique_wing_content', table_name='wings')
    op.drop_index('ix_unique_tag_content', table_name='tags')
    op.drop_index('ix_unique_resource_content', table_name='resources')
    op.drop_index('ix_unique_room_content', table_name='rooms')
    op.drop_index('ix_unique_question_content', table_name='questions')
    op.create_unique_constraint('offices_name_key', 'offices', ['name'])
    op.drop_index('ix_unique_office_content', table_name='offices')
    op.drop_index('ix_unique_location_content', table_name='locations')
    op.drop_index('ix_unique_floor_content', table_name='floors')
    op.drop_index('ix_unique_block_content', table_name='blocks')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('ix_unique_user_content', table_name='users')
    # ### end Alembic commands ###
