"""add question_title column to questions

Revision ID: 7747e8e2c4ac
Revises: eaca44fbeabe
Create Date: 2019-02-14 15:55:27.154954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7747e8e2c4ac'
down_revision = 'eaca44fbeabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_title', sa.String(), nullable=False, server_default="Room Feedback"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_title')
    # ### end Alembic commands ###
