"""empty message

Revision ID: 7cd567a63acb
Revises: 5355315aa157
Create Date: 2018-06-09 16:04:42.310758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd567a63acb'
down_revision = '5355315aa157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
