"""add unique constraint to structure_id

Revision ID: 84a1aa841faa
Revises: 93beb9b3a42d
Create Date: 2019-05-23 18:35:04.713759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a1aa841faa'
down_revision = '93beb9b3a42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'office_structures', ['structure_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('office_structures_structure_id_key',
                       'office_structures', type_='unique')
    # ### end Alembic commands ###
