"""user_role association table

Revision ID: 8647af58767d
Revises: e132e132ed54
Create Date: 2019-01-30 18:35:03.180785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8647af58767d'
down_revision = 'e132e132ed54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_roles_role_id_fkey', 'users_roles', type_='foreignkey')
    op.drop_constraint('users_roles_user_id_fkey', 'users_roles', type_='foreignkey')
    op.create_foreign_key(None, 'users_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users_roles', 'roles', ['role_id'], ['id'])
    op.drop_column('users_roles', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_roles', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.drop_constraint(None, 'users_roles', type_='foreignkey')
    op.create_foreign_key('users_roles_user_id_fkey', 'users_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_roles_role_id_fkey', 'users_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
