"""rename webId to structureId

Revision ID: 903c8f91f030
Revises: c8331212d4e3
Create Date: 2019-04-05 09:00:37.647825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903c8f91f030'
down_revision = 'c8331212d4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_structures', sa.Column('structure_id', sa.String(), nullable=False))
    op.drop_column('office_structures', 'web_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_structures', sa.Column('web_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('office_structures', 'structure_id')
    # ### end Alembic commands ###
