"""allow NULL values on columns abbreviation, structure_id in location table

Revision ID: 930f4073662d
Revises: 6318dcbb157a
Create Date: 2019-04-05 11:01:02.978753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930f4073662d'
down_revision = 'c349b9a2b71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('locations', 'structure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'structure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('locations', 'abbreviation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
