"""add auto_cancellation and app_bookings columns to events

Revision ID: 93beb9b3a42d
Revises: e4c4d5af3eec
Create Date: 2019-05-22 17:35:10.640899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93beb9b3a42d'
down_revision = 'e4c4d5af3eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('app_booking', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('auto_cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'auto_cancelled')
    op.drop_column('events', 'app_booking')
    # ### end Alembic commands ###
