"""add create and update timestamps on all records

Revision ID: 964435a2570d
Revises: 3c8552b8520e
Create Date: 2019-08-19 15:08:22.776949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '964435a2570d'
down_revision = '3c8552b8520e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('devices', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('events', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('locations', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('locations', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('notifications', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('office_structures', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('office_structures', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('resources', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('resources', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('responses', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('responses', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('room_resources', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('room_resources', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('rooms', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('rooms', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('structures', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('structures', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tags', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tags', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_updated')
    op.drop_column('users', 'date_created')
    op.drop_column('tags', 'date_updated')
    op.drop_column('tags', 'date_created')
    op.drop_column('structures', 'date_updated')
    op.drop_column('structures', 'date_created')
    op.drop_column('rooms', 'date_updated')
    op.drop_column('rooms', 'date_created')
    op.drop_column('room_resources', 'date_updated')
    op.drop_column('room_resources', 'date_created')
    op.drop_column('roles', 'date_updated')
    op.drop_column('roles', 'date_created')
    op.drop_column('responses', 'date_updated')
    op.drop_column('responses', 'date_created')
    op.drop_column('resources', 'date_updated')
    op.drop_column('resources', 'date_created')
    op.drop_column('questions', 'date_updated')
    op.drop_column('questions', 'date_created')
    op.drop_column('office_structures', 'date_updated')
    op.drop_column('office_structures', 'date_created')
    op.drop_column('notifications', 'date_updated')
    op.drop_column('notifications', 'date_created')
    op.drop_column('locations', 'date_updated')
    op.drop_column('locations', 'date_created')
    op.drop_column('events', 'date_updated')
    op.drop_column('events', 'date_created')
    op.drop_column('devices', 'date_updated')
    op.drop_column('devices', 'date_created')
    # ### end Alembic commands ###
