"""add firebase_token column to room model

Revision ID: 9d3dac6d5792
Revises: ccf47867f5e1
Create Date: 2019-02-06 06:48:34.860392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3dac6d5792'
down_revision = 'ccf47867f5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
