"""refactor response model

Revision ID: a5a4841351d7
Revises: aabedbfac0dd
Create Date: 2019-05-09 13:16:13.552409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a5a4841351d7'
down_revision = 'aabedbfac0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    questiontype = postgresql.ENUM(
        'check', 'text_area', 'rate', name='questiontype')
    questiontype.create(op.get_bind())
    op.add_column('responses', sa.Column('question_type', sa.Enum(
        'rate', 'check', 'text_area', 'missing_items', name='questiontype'),
         nullable=True))
    op.add_column('responses', sa.Column(
        'response', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('responses', 'text_area')
    op.drop_column('responses', 'check')
    op.drop_column('responses', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column(
        'rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column(
        'check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column(
        'text_area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('responses', 'response')
    op.drop_column('responses', 'question_type')
    # ### end Alembic commands ###
