"""Add state column to Structure model

Revision ID: a6afb35a9c46
Revises: f960459f3067
Create Date: 2019-05-02 14:33:18.511173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6afb35a9c46'
down_revision = 'f960459f3067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_structures', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office_structures', 'state')
    # ### end Alembic commands ###
