"""add structure id to room model

Revision ID: a71a0712c4a7
Revises: c349b9a2b71a
Create Date: 2019-03-05 08:06:22.217990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71a0712c4a7'
down_revision = 'c349b9a2b71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('structure_id', sa.Integer(), nullable=False))
    op.create_foreign_key('rooms_structure_id_fkey', 'rooms', 'structure', ['structure_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_structure_id_fkey', 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'structure_id')
    # ### end Alembic commands ###
