"""Add room cancellation_duration column

Revision ID: a7945f07140d
Revises: 6046c7c7c022
Create Date: 2018-12-11 11:34:02.449456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7945f07140d'
down_revision = '814b5dc14d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('cancellation_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'cancellation_duration')
    # ### end Alembic commands ###
