"""Rename equipment to resource and add imageurl to location and room

Revision ID: a7fc34f1c782
Revises: ac24ca4bf493
Create Date: 2018-05-07 09:21:57.353042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fc34f1c782'
down_revision = 'ac24ca4bf493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('equipments')
    op.add_column('locations', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image_url')
    op.drop_column('locations', 'image_url')
    op.create_table('equipments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='equipments_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='equipments_pkey')
    )
    op.drop_table('resources')
    # ### end Alembic commands ###
