"""empty message

Revision ID: ab16ca2af509
Revises: 4ca64ca51a57
Create Date: 2018-04-27 21:50:26.783190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab16ca2af509'
down_revision = '4ca64ca51a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
