"""Refactor Resource and RoomResource Tables

Revision ID: ac2686b45596
Revises: f960459f3067
Create Date: 2019-05-03 17:11:29.139367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2686b45596'
down_revision = 'f960459f3067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'quantity')
    op.add_column('room_resources', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_resources', 'name')
    op.add_column('resources', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
