"""modify office structure fields

Revision ID: c349b9a2b71a
Revises: defd35953750
Create Date: 2019-04-11 07:46:06.008946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c349b9a2b71a'
down_revision = 'defd35953750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_structures', sa.Column('parent_title', sa.String(), nullable=True))
    op.alter_column('office_structures', 'parent_id',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office_structures', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('office_structures', 'parent_title')
    # ### end Alembic commands ###
