"""Add event_title, start_time and end_time to events table

Revision ID: c3f8cfd2b1c4
Revises: 130957ec37be
Create Date: 2018-10-31 13:03:45.128719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f8cfd2b1c4'
down_revision = '130957ec37be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_time', sa.String(), nullable=False))
    op.add_column('events', sa.Column('event_title', sa.String(), nullable=False))
    op.add_column('events', sa.Column('start_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'event_title')
    op.drop_column('events', 'end_time')
    # ### end Alembic commands ###
