"""Fix add structure field to location model

Revision ID: c8331212d4e3
Revises: 0210dc9b2f44
Create Date: 2019-04-04 21:35:28.033312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8331212d4e3'
down_revision = '0210dc9b2f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('structure', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'structure')
    # ### end Alembic commands ###
