"""Add check_in_time and meeting_end_time to Events table

Revision ID: c900518a6daf
Revises: 4b0dfa7815d5
Create Date: 2019-03-27 15:37:09.376223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c900518a6daf'
down_revision = '4b0dfa7815d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('check_in_time', sa.String(), nullable=True))
    op.add_column('events', sa.Column('meeting_end_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'meeting_end_time')
    op.drop_column('events', 'check_in_time')
    # ### end Alembic commands ###
