"""Add structure field to location model

Revision ID: c98febd779c6
Revises: c900518a6daf
Create Date: 2019-04-01 15:24:24.178072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98febd779c6'
down_revision = 'c900518a6daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
