"""make room names unique only within a location

Revision ID: ccd30340e75a
Revises: 930f4073662d
Create Date: 2019-04-12 10:29:58.224287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd30340e75a'
down_revision = '930f4073662d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_room_in_location_content', 'rooms', ['name', 'location_id'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.drop_index('ix_unique_room_content', table_name='rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unique_room_content', 'rooms', ['name'], unique=True)
    op.drop_index('ix_unique_room_in_location_content', table_name='rooms')
    # ### end Alembic commands ###
