"""add location in room model

Revision ID: ccf47867f5e1
Revises: 404358628973
Create Date: 2019-02-05 15:14:00.657983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf47867f5e1'
down_revision = '404358628973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'location_id')
    # ### end Alembic commands ###
