"""Add devices table

Revision ID: d5f276b1a1da
Revises: 5189113ab5b6
Create Date: 2018-07-02 09:22:15.410103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f276b1a1da'
down_revision = '5189113ab5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
