"""add office

Revision ID: d6cc2e5f742f
Revises: 5189113ab5b6
Create Date: 2018-06-26 11:01:25.198656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cc2e5f742f'
down_revision = '5189113ab5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blocks', sa.Column('office_id', sa.Integer(), nullable=True))
    op.drop_constraint('blocks_location_id_fkey', 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'offices', ['office_id'], ['id'])
    op.drop_column('blocks', 'location_id')
    op.add_column('locations', sa.Column('time_zone', sa.String(), nullable=False))
    op.add_column('resources', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'quantity')
    op.drop_column('locations', 'time_zone')
    op.add_column('blocks', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key('blocks_location_id_fkey', 'blocks', 'locations', ['location_id'], ['id'])
    op.drop_column('blocks', 'office_id')
    op.drop_table('offices')
    # ### end Alembic commands ###
