"""Add admin update notifications preference

Revision ID: d6fa68a61b64
Revises: f0873fb8edb3
Create Date: 2019-07-22 12:54:15.033663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6fa68a61b64'
down_revision = 'f0873fb8edb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_notifications')
    op.add_column('devices', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'state')
    op.create_table('admin_notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_received', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_read', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('read', 'unread', name='statustype'), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='admin_notifications_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='admin_notifications_pkey')
    )
    # ### end Alembic commands ###
