"""add room labels to room model

Revision ID: defd35953750
Revises: 0ecc55aca3e7
Create Date: 2019-04-10 05:30:33.123194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'defd35953750'
down_revision = '0ecc55aca3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_labels', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_labels')
    # ### end Alembic commands ###
