"""add_soft_delete

Revision ID: e132e132ed54
Revises: c8a866f85fd7
Create Date: 2019-01-30 12:23:57.828828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e132e132ed54'
down_revision = 'c8a866f85fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    statetype = postgresql.ENUM('active', 'archived', 'deleted', name='statetype')
    statetype.create(op.get_bind())
    op.add_column('blocks', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('floors', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('locations', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('offices', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('questions', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('resources', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('rooms', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    op.add_column('wings', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wings', 'state')
    op.drop_column('users', 'state')
    op.drop_column('rooms', 'state')
    op.drop_column('resources', 'state')
    op.drop_column('questions', 'state')
    op.drop_column('offices', 'state')
    op.drop_column('locations', 'state')
    op.drop_column('floors', 'state')
    op.drop_column('blocks', 'state')

    statetype = postgresql.ENUM('active', 'archived', 'deleted', name='statetype')
    statetype.drop(op.get_bind())
    # ### end Alembic commands ###
