"""Add structure_id column to rooms table

Revision ID: e4c4d5af3eec
Revises: ac2686b45596
Create Date: 2019-05-06 15:51:42.983784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c4d5af3eec'
down_revision = 'ac2686b45596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('structure_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'structure_id')
    # ### end Alembic commands ###
