"""add soft delete to events

Revision ID: eaca44fbeabe
Revises: f480d7953daa
Create Date: 2019-02-06 07:00:32.174447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaca44fbeabe'
down_revision = 'f480d7953daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('state', sa.Enum('active', 'archived', 'deleted', name='statetype'), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'state')
    # ### end Alembic commands ###
