"""add firebase token column to room moodel2

Revision ID: f480d7953daa
Revises: 9d3dac6d5792
Create Date: 2019-02-06 09:58:52.207689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f480d7953daa'
down_revision = '9d3dac6d5792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('firebase_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'firebase_token')
    # ### end Alembic commands ###
