"""empty message

Revision ID: f62fcdba9d02
Revises: 286e9c1b8bb9
Create Date: 2018-05-07 16:29:55.661384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62fcdba9d02'
down_revision = '286e9c1b8bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
