"""Change parent_id to String in the Structures Model

Revision ID: f960459f3067
Revises: 3942aff720bb
Create Date: 2019-04-25 20:22:17.983064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f960459f3067'
down_revision = '3942aff720bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office_structures', 'parent_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               nullable=True,
               postgresql_using='parent_id::varchar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('office_structures', 'parent_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               nullable=True,
               postgresql_using='parent_id::integer')
    # ### end Alembic commands ###
