"""empty message

Revision ID: fef8e671f217
Revises: 2cc1f3a034c9
Create Date: 2018-04-27 22:00:48.531115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef8e671f217'
down_revision = '2cc1f3a034c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
