  apiVersion: v1
  kind: Pod
  metadata:
      name: converge-api-pod
  spec:
    containers:
      - name: mrm-db
        image: postgres:9.6.5-alpine
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: "mrm_test_db"
          - name: POSTGRES_PASSWORD
            value: ""
      - name: mrm-api
        image: gcr.io/andela-learning/converge-backend-jenkins:latest
        command:
        - cat
        tty: true
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: TEST_DATABASE_URL
            value: postgresql://postgres@localhost/mrm_test_db
        securityContext:
            privileged: true
    volumes:
      - name: docker-graph-storage
        emptyDir: {}
