import graphene

from graphene_sqlalchemy import (SQLAlchemyObjectType)
from sqlalchemy import func
from graphql import GraphQLError
from api.floor.models import Floor
from api.wing.models import Wing as WingModel
from utilities.validations import validate_empty_fields
from utilities.utility import update_entity_fields
from helpers.auth.authentication import Auth
from helpers.auth.error_handler import SaveContextManager
from helpers.auth.admin_roles import admin_roles


class Wing(SQLAlchemyObjectType):
    """
        Autogenerated return type of a wing
    """
    class Meta:
        model = WingModel


class CreateWing(graphene.Mutation):
    """
        Returns payload on creation of a new wing
    """
    class Arguments:
        name = graphene.String(required=True)
        floor_id = graphene.Int(required=True)

    wing = graphene.Field(Wing)

    @Auth.user_roles('Admin')
    def mutate(self, info, **kwargs):
        validate_empty_fields(**kwargs)
        floor = Floor.query.filter_by(id=kwargs['floor_id']).first()
        if not floor:
            raise GraphQLError("Floor not found")
        admin_roles.check_office_location_create_wing(floor_id=kwargs['floor_id'])  # noqa: E501
        admin_roles.create_update_delete_wing()
        wing = WingModel(**kwargs)
        payload = {
            'model': WingModel, 'field': 'name', 'value':  kwargs['name']
        }
        with SaveContextManager(
          wing, 'Wing', payload
        ):
            return CreateWing(wing=wing)


class DeleteWing(graphene.Mutation):
    """
        Returns field type of a wing
    """
    class Arguments:
        wing_id = graphene.Int(required=True)
        state = graphene.String()

    wing = graphene.Field(Wing)

    @Auth.user_roles('Admin')
    def mutate(self, info, wing_id, **kwargs):
        query_wing = Wing.get_query(info)
        result = query_wing.filter(WingModel.state == "active")
        exact_wing = result.filter(
            WingModel.id == wing_id).first()
        if not exact_wing:
            raise GraphQLError("Wing not found")
        admin_roles.create_update_delete_wing()
        update_entity_fields(exact_wing, state="archived", **kwargs)
        exact_wing.save()
        return DeleteWing(wing=exact_wing)


class UpdateWing(graphene.Mutation):
    """
        Returns payload on updating a wing
    """
    class Arguments:
        name = graphene.String()
        wing_id = graphene.Int()

    wing = graphene.Field(Wing)

    @Auth.user_roles('Admin')
    def mutate(self, info, wing_id, **kwargs):
        validate_empty_fields(**kwargs)
        get_wing = Wing.get_query(info)
        result = get_wing.filter(WingModel.state == "active")
        exact_wing = result.filter(WingModel.id == wing_id).first()
        if not exact_wing:
            raise GraphQLError("Wing not found")
        admin_roles.create_update_delete_wing()
        update_entity_fields(exact_wing, **kwargs)
        payload = {
            'model': WingModel, 'field': 'name', 'value':  kwargs['name']
        }
        with SaveContextManager(
           exact_wing, 'Wing', payload
        ):
            return UpdateWing(wing=exact_wing)


class Query(graphene.ObjectType):
    """
        Query to get wings
    """
    all_wings = graphene.List(
        Wing,
        description="Returns a list of wings and accepts the following arguments\
            \n- id: Unique identifier of the room[required]\
            \n- name: The name of the wing[required]\
            \n- floorId: the specific floor where the wing is found\
            \n- state: Checks the status of the wing if it exists\
            \n- floor: floor name where the wing is found\
            \n- rooms: rooms found in the specific wing")

    def resolve_all_wings(self, info):
        query = Wing.get_query(info)
        result = query.filter(WingModel.state == "active")
        return result.order_by(
            func.lower(WingModel.name)).all()


class Mutation(graphene.ObjectType):
    """
        Mutation to create, delete and update a wing
    """
    create_wing = CreateWing.Field(
        description="Creates a new wing with the arguments\n\
            \n- name: The name field of the wing\n\
            \n- floorId: The  unique identifierof the floor where the wing is \
            found")
    delete_wing = DeleteWing.Field(description="Deletes a given wing, takes a\
        arguments \n- wing_id: Unique id field of a wing[required]\n\
            \n- state: Check if the wing is active, archived or deleted")
    update_wing = UpdateWing.Field(description="Updates the wing details and\
        takes arguments \n- name: The name field of the wing\n\
            \n- wing_id: The unique identifier of a wing")
